package in.gov.udiseplus.kv.report.bean;

import lombok.Data;

@Data
public class TeacherProfile {
    private int teacherId;
    private String teacherName;
    private String teacherGender;
    private String teacherDob;
    private String teacherEmployeeCode;
    private Object teacherSocialCategory;
    private String teacherMobile;
    private String teacherEmail;
    private Object teacherReligion;
    private Object teacherNationality;
    private Object teacherBloodGroup;
    private String teacherPermanentAddress;
    private String teacherParmanentState;
    private String teacherPermanentDistrict;
    private String teacherPermanentPin;
    private String teacherCorrespondenceAddress;
    private String teacherCorrespondenceState;
    private String teacherCorrespondenceDistrict;
    private String teacherCorrespondencePin;
    private Object teacherPersonnelIdentification;
    private Object teacherPanNumber;
    private Object teacherAadhaarNumber;
    private Object teacherPassportNumber;
    private String teacherDisabilityYn;
    private String teacherDisabilityType;
    private Object teacherDisabilityFromBirthYn;
    private Object teacherDisabilityDate;
    private Object teacherDisabilityPrcnt;
    private Object teacherDisabilityCertAuthority;
    private Object teacherDisabilityCertNumber;
    private Object teacherTempId;
    private Object teacherSystemGeneratedCode;
    private String currentUdiseSchCode;
    private String kvCode;
    private String schoolId;
    private Object teacherAccountId;
    private String createdBy;
    private Object createdTime;
    private String modifiedBy;
    private Object modifiedTime;
    private Object verifiedType;
    private Object versionNo;
    private String teachingNonteaching;
    private Object udiseSchoolName;
    private Object teacherAge;
    private Object workExperiencePositionTypePresentKv;
    private String workExperienceWorkStartDatePresentKv;
    private Object workExperienceIdPresentKv;
    private Object workExperiencePositionTypePresentStationStartDate;
    private Object lastPromotionId;
    private String lastPromotionPositionType;
    private String lastPromotionPositionDate;
    private String workExperienceAppointedForSubject;
    private Object dropBoxFlag;
    private Object verifyFlag;
    private Object transfered_udise_sch_code;
    private Object dropbox_feedback;
    private Object dropboxDate;
    private Object tetQualifiedYn;
    private Object tetQualifingYear;
    private String natureOfAppointment;
    private Object spouseName;
    private Object spouseEmpCode;
    private Object spousePost;
    private Object spouseStationCode;
    private Object spouseStationName;
    private Object spouseStatus;
    private Object maritalStatus;
    private Object schoolRemarks;
    private Object teacherRemarks;
    private Object singleParentStatusYn;
    private Object specialRecruitmentYn;
    private Object shiftChangeSameSchool;
    private Object postName;
    private Object subjectName;
    private Object form1Status;
    private Object form2Status;
    private Object form3Status;
    private Object form4Status;
    private Object form5Status;
    private Object form6Status;
    private Object form7Status;
    private Object finalStatus;
    private Object id;
    private Object tid;
}


